<h1>Problem 1: Factorials using numpy</h1>
<li><b>prod</b> A numpy function that returns the product of all elements in an array
<li><b>cumprod</b> A numpy function on an ndarray of size n that returns an array of size n where each element i is the product of all elements from 0 to i


In [239]:
"""
Replace pass with the code that uses ndarray, prod and cumprod 
to calculate the factorial of n

The function should take an integer as an argument and return an integer

"""
def factorial(n):
    import numpy as np
    return np.arange(1,n+1).prod()
factorial(5)

120

In [240]:
"""
Replace pass with the code that uses ndarray, prod and cumprod to 
calculate the factorials of all values from 1 to n

The function should take an integer as an argument and return an ndarray
of size n 

"""

def all_factorials(n):
    import numpy as np
    return np.arange(1,n+1).cumprod()
all_factorials(5)

array([  1,   2,   6,  24, 120], dtype=int32)

<h1>Problem 2: Percent changes</h1>
Write a function that constructs an ndarray from data in a file and 
returns a 1-period percent change on an ndarray after removing any nan values. Your function must make use of the following functions:
<li>np.genfromtxt: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.genfromtxt.html
<li>np.diff: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html
<li>np.isnan: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.isnan.html

<p>Test your function out using the attached apple.csv file. Your function can assume that the file structure is (date,price)

<p>Note that percent change is defined as (p(t)-p(t-1))/p(t-1)

<b>Example:</b><br>
If the data array is: np.array([1,2,np.NaN,4,8,np.NAN])
<br>
The output array should be<br>
array([ 1.,  1.,  1.])


In [241]:
def get_pct_changes(file_name):
    import numpy as np
    data = np.genfromtxt(file_name, usecols=1, delimiter=',', skip_header=True)
    pct = np.diff(data[~np.isnan(data)])/data[~np.isnan(data)][:-1]
    return pct
get_pct_changes('apple.csv')

array([-0.05217305, -0.07339571,  0.02475207, ..., -0.00977899,
       -0.00882215,  0.01720356])

<h1>Problem 3: Pandas Grouping</h1>
Write a program that reads timeseries pricing data from a file into a pandas dataframe and then groups the data as follows:
<li>Adds a column, one-day percent change to the file 
<li>Groups the data into four categories:
<ul>
<li>"High+" if the percent change is greater than 2.5%
<li>"Low+" if the percent change is positive and less than or equal to 2.5% 
<li>"Low-" if the percent change is negative but greater than or equal to -2.5%
<li>"High-" if the percent change is less than -2.5%
</ul>
<li>Report the size and the mean of each of the groups



In [242]:
datafile = "apple.csv"
import pandas as pd
import numpy as np
df = pd.read_csv('apple.csv',na_values='null')
df['pct'] = df['Adj Close'].pct_change()
df['category'] = np.select([(df["pct"]>0.025),((df["pct"]>=0)&(df["pct"]<=0.025)),((0>df["pct"])&(df["pct"]>=(-0.025))),(df["pct"]<(-0.025))],["High+","Low+","Low-","High-"])
size = df.groupby(['category']).size()
mean = df.groupby(['category']).mean()

In [243]:
size

category
0           1
High+    1391
High-    1210
Low+     3536
Low-     3140
dtype: int64

In [244]:
mean

Adj Close       pct
category                     
0          0.421597       NaN
High+      8.652295  0.045705
High-      8.289065 -0.044220
Low+      23.738642  0.009879
Low-      24.183470 -0.011171

In [245]:
df

Date   Adj Close       pct category
0     1980-12-12    0.421597       NaN        0
1     1980-12-15    0.399601 -0.052173    High-
2     1980-12-16    0.370272 -0.073396    High-
3     1980-12-17    0.379437  0.024752     Low+
4     1980-12-18    0.390436  0.028988    High+
...          ...         ...       ...      ...
9273  2017-09-20  156.070007 -0.016758     Low-
9274  2017-09-21  153.389999 -0.017172     Low-
9275  2017-09-22  151.889999 -0.009779     Low-
9276  2017-09-25  150.550003 -0.008822     Low-
9277  2017-09-26  153.139999  0.017204     Low+

[9278 rows x 4 columns]